# Generated by Django 4.1.2 on 2022-12-07 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('document', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
